import Blake3

/-! The specification's sections 2.2 to 3.3 again, over any word type.

The text between the markers is `generate.py`'s output for `BLAKE3.md`, the same text as in
`Blake3.lean`, inserted by `emit.py`, which checks the two copies are equal. Here `Word` and
`Counter` are variables with just the operations the text uses: addition, xor, the numerals,
rotation, and the counter's two words. `Bridge.lean` proves that at `UInt32` this is the
specification's compression function, and `Emit.lean` runs it over symbolic terms. -/

namespace Blake3Generic

open Blake3 (lo hi)

/-- Rotation, the one operation on words of section 3 beyond `+`, `^^^`, and the numerals. -/
class Rotr (Word : Type) where
  rotr : Word → Nat → Word

/-- The counter's two words, `t[0]` and `t[1]`. -/
class Halves (Counter Word : Type) where
  low : Counter → Word
  high : Counter → Word

open Rotr Halves

section
variable {Word Counter : Type} [Add Word] [XorOp Word] [(n : Nat) → OfNat Word n] [Rotr Word] [Halves Counter Word]

-- BEGIN GENERATED by generate.py from BLAKE3.md, sections 2.2 to 3.3: edit BLAKE3.md, then run `generate.py --write`.

/-- Section 2.2: the initial value. -/
def IV : Vector Word 8 :=
  #v[0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]

/-- Section 2.3: the message word permutation; position `i` takes word `PERMUTATION[i]`. -/
def PERMUTATION : Vector (Fin 16) 16 :=
  #v[2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]

/-- Section 2.3: the permuted array consists of `m[PERMUTATION[0]], m[PERMUTATION[1]], ...`. -/
def PERMUTE (m : Vector Word 16) : Vector Word 16 :=
  Vector.ofFn fun i => m[PERMUTATION[i]]

/-! Section 2.4: the compression function flags. -/
def CHUNK_START : Word := 0x01
def CHUNK_END : Word := 0x02
def PARENT : Word := 0x04
def ROOT : Word := 0x08
def KEYED_HASH : Word := 0x10
def DERIVE_KEY_CONTEXT : Word := 0x20
def DERIVE_KEY_MATERIAL : Word := 0x40

/-- Section 3.2: the quarter-round function G. -/
def G (v : Vector Word 16) (a b c d : Fin 16) (x y : Word) : Vector Word 16 := Id.run do
  let mut v := v
  v := v.set a (v[a] + v[b] + x)
  v := v.set d (rotr (v[d] ^^^ v[a]) 16)
  v := v.set c (v[c] + v[d])
  v := v.set b (rotr (v[b] ^^^ v[c]) 12)
  v := v.set a (v[a] + v[b] + y)
  v := v.set d (rotr (v[d] ^^^ v[a]) 8)
  v := v.set c (v[c] + v[d])
  v := v.set b (rotr (v[b] ^^^ v[c]) 7)
  return v

/-- Section 3.3: the compression function. -/
def BLAKE3_COMPRESS (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :
    Vector Word 16 := Id.run do
  let mut v : Vector Word 16 := Vector.replicate 16 0
  let mut m := m
  v := v.set 0 h[0]
  v := v.set 1 h[1]
  v := v.set 2 h[2]
  v := v.set 3 h[3]
  v := v.set 4 h[4]
  v := v.set 5 h[5]
  v := v.set 6 h[6]
  v := v.set 7 h[7]
  v := v.set 8 IV[0]
  v := v.set 9 IV[1]
  v := v.set 10 IV[2]
  v := v.set 11 IV[3]
  v := v.set 12 (low t)
  v := v.set 13 (high t)
  v := v.set 14 len
  v := v.set 15 flags
  for _ in [0:7] do
    v := G v 0 4 8 12 m[0] m[1]
    v := G v 1 5 9 13 m[2] m[3]
    v := G v 2 6 10 14 m[4] m[5]
    v := G v 3 7 11 15 m[6] m[7]
    v := G v 0 5 10 15 m[8] m[9]
    v := G v 1 6 11 12 m[10] m[11]
    v := G v 2 7 8 13 m[12] m[13]
    v := G v 3 4 9 14 m[14] m[15]
    m := PERMUTE m
  for i in List.finRange 8 do
    v := v.set (lo i) (v[lo i] ^^^ v[hi i])
    v := v.set (hi i) (v[hi i] ^^^ h[i])
  return v

/-- Section 3.3's statements, with `v` recorded at the end of each round (the appendix's
`after round` values). -/
def BLAKE3_COMPRESS_TRACE (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :
    Array (Vector Word 16) := Id.run do
  let mut v : Vector Word 16 := Vector.replicate 16 0
  let mut m := m
  let mut trace : Array (Vector Word 16) := #[]
  v := v.set 0 h[0]
  v := v.set 1 h[1]
  v := v.set 2 h[2]
  v := v.set 3 h[3]
  v := v.set 4 h[4]
  v := v.set 5 h[5]
  v := v.set 6 h[6]
  v := v.set 7 h[7]
  v := v.set 8 IV[0]
  v := v.set 9 IV[1]
  v := v.set 10 IV[2]
  v := v.set 11 IV[3]
  v := v.set 12 (low t)
  v := v.set 13 (high t)
  v := v.set 14 len
  v := v.set 15 flags
  for _ in [0:7] do
    v := G v 0 4 8 12 m[0] m[1]
    v := G v 1 5 9 13 m[2] m[3]
    v := G v 2 6 10 14 m[4] m[5]
    v := G v 3 7 11 15 m[6] m[7]
    v := G v 0 5 10 15 m[8] m[9]
    v := G v 1 6 11 12 m[10] m[11]
    v := G v 2 7 8 13 m[12] m[13]
    v := G v 3 4 9 14 m[14] m[15]
    m := PERMUTE m
    trace := trace.push v
  return trace

-- END GENERATED

end
end Blake3Generic
