-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [stackcore]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace stackcore

/-- Trait declaration: [stackcore::Parent]
    Source: 'src/../../../../../../src/stack_core.rs', lines 7:0-9:1
    Visibility: public -/
structure Parent (Self : Type) where
  parent : Self → Array Std.U8 32#usize → Array Std.U8 32#usize → Result
    (Array Std.U8 32#usize)

/-- [stackcore::CvStack]
    Source: 'src/../../../../../../src/stack_core.rs', lines 13:0-16:1
    Visibility: public -/
structure CvStack where
  cvs : Option (Array (Array Std.U8 32#usize) 55#usize)
  len : Std.Usize

/-- [stackcore::{impl core::clone::Clone for stackcore::CvStack}::clone]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 19:4-21:5
    Visibility: public -/
def CvStack.Insts.CoreCloneClone.clone (self : CvStack) : Result CvStack := do
  ok self

/-- Trait implementation: [stackcore::{impl core::clone::Clone for stackcore::CvStack}]
    Source: 'src/../../../../../../src/stack_core.rs', lines 18:0-22:1 -/
@[reducible]
def CvStack.Insts.CoreCloneClone : core.clone.Clone CvStack := {
  clone := CvStack.Insts.CoreCloneClone.clone
}

/-- [stackcore::{stackcore::CvStack}::new]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 25:4-27:5
    Visibility: public -/
def CvStack.new : Result CvStack := do
  ok { cvs := none, len := 0#usize }

/-- [stackcore::{stackcore::CvStack}::len]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 29:4-31:5
    Visibility: public -/
def CvStack.impl.len (self : CvStack) : Result Std.Usize := do
  ok self.len

/-- [stackcore::{stackcore::CvStack}::get]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 34:4-40:5
    Visibility: public -/
def CvStack.get
  (self : CvStack) (i : Std.Usize) : Result (Array Std.U8 32#usize) := do
  massert (i < self.len)
  match self.cvs with
  | none => fail panic
  | some cvs => Array.index_usize cvs i

/-- [stackcore::{stackcore::CvStack}::push]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 43:4-51:5
    Visibility: public -/
def CvStack.push
  (self : CvStack) (cv : Array Std.U8 32#usize) : Result CvStack := do
  let b := core.option.Option.is_none self.cvs
  let o ←
    if b
    then
      let a := Array.repeat 32#usize 0#u8
      let a1 := Array.repeat 55#usize a
      ok (some a1)
    else ok self.cvs
  let o1 ←
    match o with
    | none => ok none
    | some cvs => do
                  let a ← Array.update cvs self.len cv
                  ok (some a)
  let i ← self.len + 1#usize
  ok { cvs := o1, len := i }

/-- [stackcore::{stackcore::CvStack}::clear]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 53:4-55:5
    Visibility: public -/
def CvStack.clear (self : CvStack) : Result CvStack := do
  ok { self with len := 0#usize }

/-- [stackcore::{stackcore::CvStack}::merge]: loop body 0:
    Source: 'src/../../../../../../src/stack_core.rs', lines 61:8-68:9
    Visibility: public -/
@[rust_loop_body]
def CvStack.merge_loop.body
  {P : Type} (ParentInst : Parent P) (p : P) (target : Std.Usize)
  (self : CvStack) :
  Result (ControlFlow CvStack ((Option (Array (Array Std.U8 32#usize)
    55#usize)) × Std.Usize))
  := do
  massert ((¬ (self.len > target)) || (self.len >= 2#usize))
  if self.len > target
  then
    let o ←
      match self.cvs with
      | none => ok none
      | some cvs =>
        do
        let i ← self.len - 2#usize
        let a ← Array.index_usize cvs i
        let i1 ← self.len - 1#usize
        let a1 ← Array.index_usize cvs i1
        let parent ← ParentInst.parent p a a1
        let a2 ← Array.update cvs i parent
        ok (some a2)
    let i ← self.len - 1#usize
    ok (cont { cvs := o, len := i })
  else ok (done (self.cvs, self.len))

/-- [stackcore::{stackcore::CvStack}::merge]: loop 0:
    Source: 'src/../../../../../../src/stack_core.rs', lines 61:8-68:9
    Visibility: public -/
@[rust_loop]
def CvStack.merge_loop
  {P : Type} (ParentInst : Parent P) (self : CvStack) (p : P)
  (target : Std.Usize) :
  Result ((Option (Array (Array Std.U8 32#usize) 55#usize)) × Std.Usize)
  := do
  loop
    (fun self1 => CvStack.merge_loop.body ParentInst p target self1)
    self

/-- [stackcore::{stackcore::CvStack}::merge]:
    Source: 'src/../../../../../../src/stack_core.rs', lines 60:4-69:5
    Visibility: public -/
def CvStack.merge
  {P : Type} (ParentInst : Parent P) (self : CvStack) (p : P)
  (target : Std.Usize) :
  Result CvStack
  := do
  let (o, i) ← CvStack.merge_loop ParentInst self p target
  ok { cvs := o, len := i }

/-- [stackcore::DEPTH]
    Source: 'src/lib.rs', lines 6:0-6:28
    Visibility: public -/
@[global_simps, irreducible] def DEPTH : Std.Usize := 55#usize

end stackcore
