-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [treecore]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace treecore

/-- [treecore::CHUNK_LEN]
    Source: 'src/lib.rs', lines 4:0-4:34
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_LEN : Std.Usize := 1024#usize

/-- Trait declaration: [treecore::Kernels]
    Source: 'src/lib.rs', lines 8:0-14:1
    Visibility: public -/
structure Kernels (Self : Type) where
  chunk : Self → Slice Std.U8 → Std.U64 → Result (Array Std.U32 8#usize)
  parent : Self → Array Std.U32 8#usize → Array Std.U32 8#usize → Result
    (Array Std.U32 8#usize)

/-- [treecore::left_len]: loop body 0:
    Source: 'src/lib.rs', lines 21:4-23:5
    Visibility: public -/
@[rust_loop_body]
def left_len_loop.body
  (chunks : Std.Usize) (p : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i ← chunks / 2#usize
  if p <= i
  then let p1 ← p * 2#usize
       ok (cont p1)
  else ok (done p)

/-- [treecore::left_len]: loop 0:
    Source: 'src/lib.rs', lines 21:4-23:5
    Visibility: public -/
@[rust_loop]
def left_len_loop (chunks : Std.Usize) (p : Std.Usize) : Result Std.Usize := do
  loop
    (fun p1 => left_len_loop.body chunks p1)
    p

/-- [treecore::left_len]:
    Source: 'src/lib.rs', lines 18:0-25:1
    Visibility: public -/
def left_len (len : Std.Usize) : Result Std.Usize := do
  let i ← len - 1#usize
  let chunks ← i / CHUNK_LEN
  let p ← left_len_loop chunks 1#usize
  p * CHUNK_LEN

/-- [treecore::subtree]:
    Source: 'src/lib.rs', lines 29:0-38:1
    Visibility: public -/
def subtree
  {K : Type} (KernelsInst : Kernels K) (k : K) (input : Slice Std.U8)
  (counter : Std.U64) :
  Result (Array Std.U32 8#usize)
  := do
  let i := Slice.len input
  if i <= CHUNK_LEN
  then KernelsInst.chunk k input counter
  else
    let i1 := Slice.len input
    let l ← left_len i1
    let (a, b) ← core.slice.Slice.split_at input l
    let left ← subtree KernelsInst k a counter
    let i2 ← l / CHUNK_LEN
    let i3 ← lift (UScalar.cast .U64 i2)
    let i4 ← counter + i3
    let right ← subtree KernelsInst k b i4
    KernelsInst.parent k left right
partial_fixpoint

end treecore
