-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [widecore]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace widecore

/-- Trait declaration: [widecore::Kernels]
    Source: 'src/../../../../../../src/tree_core.rs', lines 8:0-22:1
    Visibility: public -/
structure Kernels (Self : Type) where
  degree : Self → Result Std.Usize
  chunks : Self → Slice Std.U8 → Std.U64 → Slice (Array Std.U8 32#usize)
    → Result (Std.Usize × (Slice (Array Std.U8 32#usize)))
  parents : Self → Slice (Array Std.U8 32#usize) → Slice (Array Std.U8
    32#usize) → Result (Std.Usize × (Slice (Array Std.U8 32#usize)))
  subtree : Self → Slice Std.U8 → Std.Usize → Std.U64 → Slice (Array
    Std.U8 32#usize) → Result ((Option Std.Usize) × (Slice (Array Std.U8
    32#usize)))

/-- [widecore::CHUNK_LEN]
    Source: 'src/lib.rs', lines 6:0-6:34
    Visibility: public -/
@[global_simps, irreducible] def CHUNK_LEN : Std.Usize := 1024#usize

/-- [widecore::left_len]: loop body 0:
    Source: 'src/../../../../../../src/tree_core.rs', lines 29:4-31:5
    Visibility: public -/
@[rust_loop_body]
def left_len_loop.body
  (chunks : Std.Usize) (p : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i ← chunks / 2#usize
  if p <= i
  then let p1 ← p * 2#usize
       ok (cont p1)
  else ok (done p)

/-- [widecore::left_len]: loop 0:
    Source: 'src/../../../../../../src/tree_core.rs', lines 29:4-31:5
    Visibility: public -/
@[rust_loop]
def left_len_loop (chunks : Std.Usize) (p : Std.Usize) : Result Std.Usize := do
  loop
    (fun p1 => left_len_loop.body chunks p1)
    p

/-- [widecore::left_len]:
    Source: 'src/../../../../../../src/tree_core.rs', lines 26:0-33:1
    Visibility: public -/
def left_len (len : Std.Usize) : Result Std.Usize := do
  let i ← len - 1#usize
  let chunks ← i / CHUNK_LEN
  let p ← left_len_loop chunks 1#usize
  p * CHUNK_LEN

/-- [widecore::wide]:
    Source: 'src/../../../../../../src/tree_core.rs', lines 39:0-60:1
    Visibility: public -/
def wide
  {K : Type} (KernelsInst : Kernels K) (k : K) (input : Slice Std.U8)
  (ahead : Std.Usize) (counter : Std.U64) (out : Slice (Array Std.U8 32#usize))
  :
  Result (Std.Usize × (Slice (Array Std.U8 32#usize)))
  := do
  let i := Slice.len input
  let i1 ← KernelsInst.degree k
  let i2 ← i1 * CHUNK_LEN
  if i <= i2
  then KernelsInst.chunks k input counter out
  else
    let (o, out1) ← KernelsInst.subtree k input ahead counter out
    match o with
    | none =>
      let i3 := Slice.len input
      let l ← left_len i3
      let (a, b) ← core.slice.Slice.split_at input l
      let a1 := Array.repeat 32#usize 0#u8
      let cvs := Array.repeat 256#usize a1
      let (out2, left_cap) ←
        if l = CHUNK_LEN
        then ok (out1, 1#usize)
        else
          do
          let i4 ← if i1 < 2#usize
                     then ok 2#usize
                     else ok i1
          ok (out1, i4)
      let (s, to_slice_mut_back) ← lift (Array.to_slice_mut cvs)
      let ((lo, hi), split_at_mut_back) ←
        core.slice.Slice.split_at_mut s left_cap
      let i4 := Slice.len b
      let i5 ← i4 + ahead
      let (ln, lo1) ← wide KernelsInst k a i5 counter lo
      let i6 ← l / CHUNK_LEN
      let i7 ← lift (UScalar.cast .U64 i6)
      let i8 ← counter + i7
      let (rn, hi1) ← wide KernelsInst k b ahead i8 hi
      if ln = 1#usize
      then
        let a2 ← Slice.index_usize lo1 0#usize
        let out3 ← Slice.update out2 0#usize a2
        let a3 ← Slice.index_usize hi1 0#usize
        let out4 ← Slice.update out3 1#usize a3
        ok (2#usize, out4)
      else
        let s1 := split_at_mut_back (lo1, hi1)
        let cvs1 := to_slice_mut_back s1
        let i9 ← ln + rn
        let s2 ←
          core.array.Array.index (core.ops.index.IndexSlice
            (core.slice.index.SliceIndexRangeToUsizeSlice (Array Std.U8
            32#usize))) cvs1 { «end» := i9 }
        KernelsInst.parents k s2 out2
    | some n => ok (n, out1)
partial_fixpoint

/-- [widecore::OUT_LEN]
    Source: 'src/lib.rs', lines 7:0-7:30
    Visibility: public -/
@[global_simps, irreducible] def OUT_LEN : Std.Usize := 32#usize

/-- [widecore::MAX]
    Source: 'src/lib.rs', lines 8:0-8:27
    Visibility: public -/
@[global_simps, irreducible] def MAX : Std.Usize := 128#usize

end widecore
