/-! # BLAKE3, as specified in `BLAKE3.md` (c2sp.org/BLAKE3, v1.0.0)

Every definition here corresponds to a section of the specification, under the same name where
it has one, and carries the relevant spec text above it.

Sections 2.2 to 3.3 (the IV, the permutation, the flags, `G`, and `BLAKE3_COMPRESS`) are generated
from `BLAKE3.md` by `generate.py`, one rule per pseudocode construct, and `check.py` requires the
generated text below to equal its output. Section 4 (the tree mode and the three hashing modes) is
prose in the specification, and is transcribed here by hand; `Theorems.lean` proves the tree's split
satisfies section 4.3.2's rules, and `Tests.lean` reproduces every value in the specification's
appendix and the official test vectors it links.

The pseudocode is transcribed as follows:

* A word is a `UInt32`, whose `+` is addition mod 2^32 (so `mod 2**32` is implicit) and `^^^` is
  `^` (xor).
* `x >>> n` (rotation right by `n` bits) is `rotr x n`.
* `v[i] := e` is `v := v.set i e`; `v[a..b] := w[c..d]` is one such assignment per index.
* `t[0]` and `t[1]` are `low t` and `high t`, the counter's low and high 32-bit words.
* `FOR i = 0 TO n DO` is `for i in List.finRange (n + 1)`, with `lo i` and `hi i` for the indices
  `i` and `i + 8` of the 16-word array.
* `PERMUTE(m)` is `m := PERMUTE m`. -/

namespace Blake3

/-- Section 2.1: BLAKE3 works with 32-bit words and arrays thereof. -/
abbrev Word := UInt32

/-- Section 3.1: `t[0..1]`, a 64-bit counter whose lower-order 32-bit word is `t[0]` and
higher-order 32-bit word is `t[1]`. -/
abbrev Counter := UInt64

/-- `t[0]`, the counter's lower-order word. -/
def low (t : Counter) : Word := t.toUInt32

/-- `t[1]`, the counter's higher-order word. -/
def high (t : Counter) : Word := (t >>> 32).toUInt32

/-- `x >>> n`: `x` rotated right by `n` bits, for `n` in 1 to 31. -/
def rotr (x : Word) (n : Nat) : Word :=
  (x >>> n.toUInt32) ||| (x <<< (32 - n).toUInt32)

/-- Index `i` of the 16-word array, for `i` in 0 to 7. -/
def lo (i : Fin 8) : Fin 16 := ⟨i.val, by omega⟩

/-- Index `i + 8` of the 16-word array, for `i` in 0 to 7. -/
def hi (i : Fin 8) : Fin 16 := ⟨i.val + 8, by omega⟩

-- BEGIN GENERATED by generate.py from BLAKE3.md, sections 2.2 to 3.3. Do not edit by hand.

/-- Section 2.2: the initial value. -/
def IV : Vector Word 8 :=
  #v[0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]

/-- Section 2.3: the message word permutation; position `i` takes word `PERMUTATION[i]`. -/
def PERMUTATION : Vector (Fin 16) 16 :=
  #v[2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]

/-- Section 2.3: the permuted array consists of `m[PERMUTATION[0]], m[PERMUTATION[1]], ...`. -/
def PERMUTE (m : Vector Word 16) : Vector Word 16 :=
  Vector.ofFn fun i => m[PERMUTATION[i]]

/-! Section 2.4: the compression function flags. -/
def CHUNK_START : Word := 0x01
def CHUNK_END : Word := 0x02
def PARENT : Word := 0x04
def ROOT : Word := 0x08
def KEYED_HASH : Word := 0x10
def DERIVE_KEY_CONTEXT : Word := 0x20
def DERIVE_KEY_MATERIAL : Word := 0x40

/-- Section 3.2: the quarter-round function G. -/
def G (v : Vector Word 16) (a b c d : Fin 16) (x y : Word) : Vector Word 16 := Id.run do
  let mut v := v
  v := v.set a (v[a] + v[b] + x)
  v := v.set d (rotr (v[d] ^^^ v[a]) 16)
  v := v.set c (v[c] + v[d])
  v := v.set b (rotr (v[b] ^^^ v[c]) 12)
  v := v.set a (v[a] + v[b] + y)
  v := v.set d (rotr (v[d] ^^^ v[a]) 8)
  v := v.set c (v[c] + v[d])
  v := v.set b (rotr (v[b] ^^^ v[c]) 7)
  return v

/-- Section 3.3: the compression function. -/
def BLAKE3_COMPRESS (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :
    Vector Word 16 := Id.run do
  let mut v : Vector Word 16 := Vector.replicate 16 0
  let mut m := m
  v := v.set 0 h[0]
  v := v.set 1 h[1]
  v := v.set 2 h[2]
  v := v.set 3 h[3]
  v := v.set 4 h[4]
  v := v.set 5 h[5]
  v := v.set 6 h[6]
  v := v.set 7 h[7]
  v := v.set 8 IV[0]
  v := v.set 9 IV[1]
  v := v.set 10 IV[2]
  v := v.set 11 IV[3]
  v := v.set 12 (low t)
  v := v.set 13 (high t)
  v := v.set 14 len
  v := v.set 15 flags
  for _ in [0:7] do
    v := G v 0 4 8 12 m[0] m[1]
    v := G v 1 5 9 13 m[2] m[3]
    v := G v 2 6 10 14 m[4] m[5]
    v := G v 3 7 11 15 m[6] m[7]
    v := G v 0 5 10 15 m[8] m[9]
    v := G v 1 6 11 12 m[10] m[11]
    v := G v 2 7 8 13 m[12] m[13]
    v := G v 3 4 9 14 m[14] m[15]
    m := PERMUTE m
  for i in List.finRange 8 do
    v := v.set (lo i) (v[lo i] ^^^ v[hi i])
    v := v.set (hi i) (v[hi i] ^^^ h[i])
  return v

/-- Section 3.3's statements, with `v` recorded at the end of each round: the appendix's
"after round i" values. -/
def BLAKE3_COMPRESS_TRACE (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :
    Array (Vector Word 16) := Id.run do
  let mut v : Vector Word 16 := Vector.replicate 16 0
  let mut m := m
  let mut trace : Array (Vector Word 16) := #[]
  v := v.set 0 h[0]
  v := v.set 1 h[1]
  v := v.set 2 h[2]
  v := v.set 3 h[3]
  v := v.set 4 h[4]
  v := v.set 5 h[5]
  v := v.set 6 h[6]
  v := v.set 7 h[7]
  v := v.set 8 IV[0]
  v := v.set 9 IV[1]
  v := v.set 10 IV[2]
  v := v.set 11 IV[3]
  v := v.set 12 (low t)
  v := v.set 13 (high t)
  v := v.set 14 len
  v := v.set 15 flags
  for _ in [0:7] do
    v := G v 0 4 8 12 m[0] m[1]
    v := G v 1 5 9 13 m[2] m[3]
    v := G v 2 6 10 14 m[4] m[5]
    v := G v 3 7 11 15 m[6] m[7]
    v := G v 0 5 10 15 m[8] m[9]
    v := G v 1 6 11 12 m[10] m[11]
    v := G v 2 7 8 13 m[12] m[13]
    v := G v 3 4 9 14 m[14] m[15]
    m := PERMUTE m
    trace := trace.push v
  return trace

-- END GENERATED

/-! ## Section 4: the tree mode of operation -/

/-- Section 2.1: "Byte streams are interpreted as words in little-endian order, with the least
significant byte first." The `n` words starting at byte `at_` of `b`; bytes past its end are zeros
(the padding of a short block, section 4.2). -/
def wordsLE (b : ByteArray) (at_ n : Nat) : Vector Word n :=
  Vector.ofFn fun i =>
    let byte (k : Nat) : Word := (b.get! (at_ + 4 * i.val + k)).toUInt32 <<< (8 * k).toUInt32
    byte 0 ||| byte 1 ||| byte 2 ||| byte 3

/-- The bytes of words, least significant byte first (section 2.1). -/
def bytesLE (ws : List Word) : ByteArray :=
  ⟨(ws.flatMap fun (w : Word) => [w.toUInt8, (w >>> 8).toUInt8, (w >>> 16).toUInt8, (w >>> 24).toUInt8]).toArray⟩

/-- The first eight words: "When processing chunks and parent nodes below the root, the output is
always truncated to the first 8 words, `v[0..7]`." -/
def first8 (v : Vector Word 16) : Vector Word 8 := Vector.ofFn fun i => v[lo i]

/-- A node of the tree, as the inputs of its last compression: a chunk's last block, or a parent's
one. Its chaining value is that compression's first eight words; if it is the root, the same
compression with the `ROOT` flag (and the output counter, section 4.4) gives the output. -/
structure Node where
  h : Vector Word 8
  m : Vector Word 16
  t : Counter
  len : Word
  flags : Word
  deriving Inhabited

/-- The node's 8-word chaining value, below the root. -/
def Node.cv (n : Node) : Vector Word 8 := first8 (BLAKE3_COMPRESS n.h n.m n.t n.len n.flags)

/-- Section 4.2: "Chunks are divided into 64-byte blocks. If the input byte length is not a multiple
of 64, the last block is short. The last block is empty if and only if the input is empty. Short or
empty blocks are padded with zeros (0x00) to be 64 bytes." The number of blocks of a chunk of
`len` bytes. -/
def blockCount (len : Nat) : Nat := max 1 ((len + 63) / 64)

/-- Section 4.2: chunk `index` of the input, `chunk` its bytes, `key` the 8-word key (section 4.1)
and `mode` the mode's flag (`0`, `KEYED_HASH`, `DERIVE_KEY_CONTEXT`, or `DERIVE_KEY_MATERIAL`).

"Each chunk is processed by iterating the compression function (1024/64 = 16 times for a full
1024-byte chunk) to process the 64-byte blocks, each parsed as 16 32-bit little-endian words.

* `h[0..7]`: For the first block of a chunk, this is the 8-word key defined above. For subsequent
  blocks, this is the truncated output of the compression of the previous block.
* `m[0..15]`: This is the block processed by the compression function.
* `t[0..1]`: The counter `t` for each block is the chunk index.
* `len`: This word is the block length, or the number of data bytes in the block, which is 64 for
  all blocks except possibly the last block of the last chunk.
* `flags`: The first block of each chunk sets the `CHUNK_START` flag, and the last block of each
  chunk sets the `CHUNK_END` flag. If a chunk contains only one block, that block sets both."

The `ROOT` flag of a root chunk's last block is the output's (section 4.4). The mode flags are set
on every compression of the mode (section 2.4). -/
def chunkNode (key : Vector Word 8) (mode : Word) (chunk : ByteArray) (index : Nat) : Node := Id.run do
  let blocks := blockCount chunk.size
  let t : Counter := index.toUInt64
  let flagsOf (j : Nat) : Word :=
    mode ||| (if j = 0 then CHUNK_START else 0) ||| (if j + 1 = blocks then CHUNK_END else 0)
  let mut h := key
  for j in [0:blocks - 1] do
    h := first8 (BLAKE3_COMPRESS h (wordsLE chunk (64 * j) 16) t 64 (flagsOf j))
  let last := blocks - 1
  return { h, m := wordsLE chunk (64 * last) 16, t, len := (chunk.size - 64 * last).toUInt32,
           flags := flagsOf last }

/-- Section 4.3.1: a parent node.

"* `h[0..7]`: This is the 8-word key defined above.
* `m[0..15]`: This is the 64-byte block consisting of the concatenated 32-byte output of the two
  child nodes.
* `t[0..1]`: The counter t is set to zero (0).
* `len`: The block length is set to 64.
* `flags`: The `PARENT` flag is set for all parent nodes. [...] The mode flags (`KEYED_HASH`,
  `DERIVE_KEY_CONTEXT`, `DERIVE_KEY_MATERIAL`) must be set for a parent node when operating in the
  respective modes." -/
def parentNode (key : Vector Word 8) (mode : Word) (left right : Vector Word 8) : Node :=
  { h := key, m := left ++ right, t := 0, len := 64, flags := mode ||| PARENT }

/-- Section 4.3.2: the number of chunks in the left subtree of a tree of `n ≥ 2` chunks, the
largest power of 2 below `n`. "Left subtrees are full, that is, each left subtree is a complete
binary tree, with all its chunks at the same depth, and a number of chunks that is a power of 2.
Left subtrees are big, that is, each left subtree contains a number of chunks greater than or equal
to the number of chunks in its sibling right subtree." `Theorems.lean` proves this number is the
one these rules allow. -/
def leftCount (n : Nat) : Nat := 2 ^ (n - 1).log2

theorem leftCount_pos (n : Nat) : 0 < leftCount n := Nat.two_pow_pos _

theorem leftCount_lt (n : Nat) (h : 2 ≤ n) : leftCount n < n := by
  have := Nat.log2_self_le (n := n - 1) (by omega)
  unfold leftCount; omega

/-- Section 4.3.2: the root node of the tree over the chunk nodes `chunks`. "If there is only one
chunk, that chunk is the root node and only node of the tree. Otherwise, the chunks are assembled
with parent nodes, each parent node having exactly two children." -/
def tree (key : Vector Word 8) (mode : Word) (chunks : Array Node) : Node :=
  go 0 chunks.size
where
  /-- The subtree over the `n ≥ 1` chunks from `start`. -/
  go (start n : Nat) : Node :=
    if _h : n ≤ 1 then chunks[start]?.getD chunks[0]!
    else
      let k := leftCount n
      parentNode key mode (go start k).cv (go (start + k) (n - k)).cv
  termination_by n
  decreasing_by
    · exact leftCount_lt n (by omega)
    · have := leftCount_pos n; omega

/-- Section 4.4: "BLAKE3, in any of its three modes, can produce outputs of any byte length up to
2^64 - 1. This is done by repeating the root compression with incrementing values of the counter t.
The results of these repeated root compressions are then concatenated to form the output, possibly
truncating the last one." Section 4.3.2: "Output of up to 64 bytes is formed by taking as many
bytes as required from the final `v[0..15]` of the root's compression function." -/
def output (root : Node) (outLen : Nat) : ByteArray :=
  let blocks := (List.range ((outLen + 63) / 64)).map fun i =>
    (BLAKE3_COMPRESS root.h root.m i.toUInt64 root.len (root.flags ||| ROOT)).toList
  (bytesLE blocks.flatten).extract 0 outLen

/-- Section 4.2: "BLAKE3's chunk processing divides the BLAKE3 input into 1024-byte chunks [...]. If
the input byte length is not a multiple of 1024, the last chunk is short. The last chunk is empty if
and only if the input is empty." Then the tree over them (4.3) and its output (4.4). -/
def blake3 (key : Vector Word 8) (mode : Word) (input : ByteArray) (outLen : Nat) : ByteArray :=
  let count := max 1 ((input.size + 1023) / 1024)
  let chunks := (Array.range count).map fun i =>
    chunkNode key mode (input.extract (1024 * i) (1024 * (i + 1))) i
  output (tree key mode chunks) outLen

/-! ## Sections 1.1 and 4.1: the hashing modes -/

/-- Unkeyed hashing (`hash`): "In the unkeyed hashing mode, the key is defined to be `IV`." -/
def hash (input : ByteArray) (outLen : Nat := 32) : ByteArray :=
  blake3 IV 0 input outLen

/-- Keyed hashing (`keyed_hash`): "the caller provides a 32-byte key parameter, and that parameter
is split into 8 little-endian words." Every compression sets `KEYED_HASH`. -/
def keyed_hash (key : ByteArray) (input : ByteArray) (outLen : Nat := 32) : ByteArray :=
  blake3 (wordsLE key 0 8) KEYED_HASH input outLen

/-- Key derivation (`derive_key`): "In the first phase (`DERIVE_KEY_CONTEXT`), the key is defined to
be `IV`, and the message is the context string. In the second phase (`DERIVE_KEY_MATERIAL`), the
key is the truncated output of the first phase, and the message is the key material." -/
def derive_key (context : ByteArray) (material : ByteArray) (outLen : Nat := 32) : ByteArray :=
  let contextKey := blake3 IV DERIVE_KEY_CONTEXT context 32
  blake3 (wordsLE contextKey 0 8) DERIVE_KEY_MATERIAL material outLen

end Blake3
