"""Generate the formal part of Blake3.lean from BLAKE3.md, deterministically.

BLAKE3.md gives sections 2.2 to 3.3 in fixed forms: the IV and the
permutation as code blocks of numbers, the flags as a list of `NAME (0xNN)`
items, and the functions G and BLAKE3_COMPRESS as pseudocode. This script
parses exactly those forms and translates each pseudocode line, one rule per
construct (below), into Lean. Anything else in a block it reads stops it
with an error, so a change to the document either regenerates cleanly or is
refused. The generated text sits between two markers in Blake3.lean, and
`check.py` requires it to equal this script's output byte for byte.

    python3 generate.py ../BLAKE3.md            # print the generated section
    python3 generate.py ../BLAKE3.md --write     # replace it in Blake3.lean

Translation rules (pseudocode -> Lean):
    v[i] := e                       v := v.set i (e)
    v[a..b] := w[c..d]              one `v := v.set` per index
    x mod 2**32                     x  (UInt32 arithmetic is mod 2^32)
    x ^ y                           x ^^^ y
    (x) >>> n                       rotr (x) n
    t[0], t[1]                      low t, high t  (the counter's 32-bit words)
    v := G( v, a, b, c, d, x, y )   v := G v a b c d x y
    PERMUTE(m)                      m := PERMUTE m
    FOR i = 0 TO n DO ... END FOR   for i in List.finRange (n+1) do ...  (a body that uses i,
                                    whose v[i] and v[i + 8] are v[lo i] and v[hi i])
                                    for _ in [0:n+1] do ...  (a body that does not)
    RETURN v                        return v
"""

import re
import sys

BEGIN = "-- BEGIN GENERATED by generate.py from BLAKE3.md, sections 2.2 to 3.3: edit BLAKE3.md, then run `generate.py --write`."
END = "-- END GENERATED"


class Refused(Exception):
    pass


def sections(md):
    """{number: text} for headings `### 2.2.  Title` and the like."""
    out, cur, buf = {}, None, []
    for line in md.splitlines():
        m = re.match(r"#{2,4}\s+(\d+(?:\.\d+)*)\.?\s", line)
        if m:
            if cur:
                out[cur] = "\n".join(buf)
            cur, buf = m.group(1), []
        elif cur:
            buf.append(line)
    if cur:
        out[cur] = "\n".join(buf)
    return out


def blocks(text):
    return re.findall(r"```\n(.*?)```", text, re.S)


def iv(sec):
    (b,) = blocks(sec)
    words = b.split()
    if len(words) != 8 or not all(re.fullmatch(r"0x[0-9a-f]{8}", w) for w in words):
        raise Refused("section 2.2: expected eight 32-bit hex words")
    return words


def permutation(sec):
    (b,) = blocks(sec)
    rows = [[int(x) for x in re.findall(r"\d+", line)] for line in b.strip().splitlines()]
    if len(rows) != 2 or rows[0] != list(range(16)) or sorted(rows[1]) != list(range(16)):
        raise Refused("section 2.3: expected the indices 0..15 and a permutation of them")
    return rows[1]


def flags(sec):
    found = re.findall(r"^\* `([A-Z_]+)` \((0x[0-9a-f]{2})\):", sec, re.M)
    if len(found) != 7:
        raise Refused("section 2.4: expected seven flags")
    return found


def pseudocode(block):
    """The statements of a FUNCTION ... END FUNCTION block: its header and
    its body lines, the `|` gutters and comments removed."""
    lines = []
    for raw in block.splitlines():
        s = raw.strip()
        if not s:
            continue
        s = re.sub(r"^(\|\s*)+", "", s)
        s = re.sub(r"\s*//.*$", "", s).strip()
        if s:
            lines.append(s)
    if not lines[0].startswith("FUNCTION") or lines[-1] != "END FUNCTION.":
        raise Refused(f"pseudocode block without FUNCTION ... END FUNCTION.: {lines[0]}")
    return lines[0], lines[1:-1]


def expr(e):
    """One pseudocode expression in Lean."""
    e = e.strip()
    e = re.sub(r"\s*mod 2\*\*32", "", e)
    e = re.sub(r"t\[0\]", "low t", e)
    e = re.sub(r"t\[1\]", "high t", e)
    m = re.fullmatch(r"\((.*)\)\s*>>>\s*(\d+)", e)
    if m:
        return f"rotr ({expr(m.group(1))}) {m.group(2)}"
    if not re.fullmatch(r"[\w\[\]\s+^.()]+", e):
        raise Refused(f"expression outside the translated forms: {e}")
    e = re.sub(r"\(\s*", "(", re.sub(r"\s*\)", ")", e))
    # v's index i ranges over Fin 8 (lo i, hi i in Fin 16); h's is i itself.
    e = re.sub(r"v\[i \+ 8\]", "v[hi i]", e)
    e = re.sub(r"v\[i\]", "v[lo i]", e)
    e = e.replace(" ^ ", " ^^^ ").strip()
    if e.startswith("(") and e.endswith(")") and balanced(e[1:-1]):
        e = e[1:-1]
    return e


def balanced(e):
    depth = 0
    for ch in e:
        depth += {"(": 1, ")": -1}.get(ch, 0)
        if depth < 0:
            return False
    return depth == 0


def wrap(e):
    """`e` as one argument: parenthesised unless it is a name or an index."""
    return e if re.fullmatch(r"[\w.]+(\[[\w ]+\])?", e) else f"({e})"


def statement(s, indent):
    pad = "  " * indent
    m = re.fullmatch(r"v\[(\d+)\.\.(\d+)\] := (\w+)\[(\d+)\.\.(\d+)\]", s)
    if m:
        a, b, src, c, d = m.group(1), int(m.group(2)), m.group(3), int(m.group(4)), int(m.group(5))
        a = int(a)
        if b - a != d - c:
            raise Refused(f"ranges of different lengths: {s}")
        return [f"{pad}v := v.set {a + k} {src}[{c + k}]" for k in range(b - a + 1)]
    m = re.fullmatch(r"v\[([\w +]+)\] := (.*)", s)
    if m:
        return [f"{pad}v := v.set {lean_index(m.group(1))} {wrap(expr(m.group(2)))}"]
    m = re.fullmatch(r"v := G\( v, (\d+), (\d+), +(\d+), (\d+), m\[ ?(\d+)\], m\[ ?(\d+)\] \)", s)
    if m:
        a, b, c, d, x, y = m.groups()
        return [f"{pad}v := G v {a} {b} {c} {d} m[{x}] m[{y}]"]
    if s == "PERMUTE(m)":
        return [f"{pad}m := PERMUTE m"]
    m = re.fullmatch(r"RETURN v(\[0\.\.15\])?", s)
    if m:
        return [f"{pad}return v"]
    raise Refused(f"statement outside the translated forms: {s}")


def lean_index(i):
    """An index expression: a number, `i`, or `i + 8` (i ranging over Fin 8)."""
    i = i.strip()
    if re.fullmatch(r"\d+", i):
        return i
    if i in ("a", "b", "c", "d"):
        return i
    if i == "i":
        return "(lo i)"
    if re.fullmatch(r"i \+ 8", i):
        return "(hi i)"
    raise Refused(f"index outside the translated forms: {i}")


def body(lines, indent):
    out, k = [], 0
    while k < len(lines):
        s = lines[k]
        m = re.fullmatch(r"FOR i = 0 TO (\d+) DO", s)
        if m:
            n = int(m.group(1)) + 1
            depth, j = 1, k + 1
            while depth:
                if lines[j].startswith("FOR "):
                    depth += 1
                if lines[j].startswith("END FOR"):
                    depth -= 1
                j += 1
            inner = lines[k + 1:j - 1]
            uses_i = any(re.search(r"\bi\b", x) for x in inner)
            out.append("  " * indent + (f"for i in List.finRange {n} do" if uses_i else f"for _ in [0:{n}] do"))
            out += body(inner, indent + 1)
            k = j
            continue
        out += statement(s, indent)
        k += 1
    return out


def generate(md):
    sec = sections(md)
    ivw = iv(sec["2.2"])
    perm = permutation(sec["2.3"])
    fl = flags(sec["2.4"])
    g_block, = [b for b in blocks(sec["3.2"]) if "FUNCTION G" in b]
    c_block, = [b for b in blocks(sec["3.3"]) if "FUNCTION BLAKE3_COMPRESS" in b]
    g_head, g_body = pseudocode(g_block)
    c_head, c_body = pseudocode(c_block)
    if g_head != "FUNCTION G( v[0..15], a, b, c, d, x, y )":
        raise Refused(f"G's header changed: {g_head}")
    if c_head != "FUNCTION BLAKE3_COMPRESS( h[0..7], m[0..15], t, len, flags )":
        raise Refused(f"BLAKE3_COMPRESS's header changed: {c_head}")
    out = [BEGIN, ""]
    out.append("/-- Section 2.2: the initial value. -/")
    out.append("def IV : Vector Word 8 :=")
    out.append("  #v[" + ", ".join(ivw) + "]")
    out.append("")
    out.append("/-- Section 2.3: the message word permutation; position `i` takes word `PERMUTATION[i]`. -/")
    out.append("def PERMUTATION : Vector (Fin 16) 16 :=")
    out.append("  #v[" + ", ".join(str(p) for p in perm) + "]")
    out.append("")
    out.append("/-- Section 2.3: the permuted array consists of `m[PERMUTATION[0]], m[PERMUTATION[1]], ...`. -/")
    out.append("def PERMUTE (m : Vector Word 16) : Vector Word 16 :=")
    out.append("  Vector.ofFn fun i => m[PERMUTATION[i]]")
    out.append("")
    out.append("/-! Section 2.4: the compression function flags. -/")
    for name, val in fl:
        out.append(f"def {name} : Word := {val}")
    out.append("")
    out.append("/-- Section 3.2: the quarter-round function G. -/")
    out.append("def G (v : Vector Word 16) (a b c d : Fin 16) (x y : Word) : Vector Word 16 := Id.run do")
    out.append("  let mut v := v")
    out += body(g_body, 1)
    out.append("")
    out.append("/-- Section 3.3: the compression function. -/")
    out.append("def BLAKE3_COMPRESS (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :")
    out.append("    Vector Word 16 := Id.run do")
    out.append("  let mut v : Vector Word 16 := Vector.replicate 16 0")
    out.append("  let mut m := m")
    out += body(c_body, 1)
    out.append("")
    # The same statements again, recording v at the end of each round (the
    # appendix's "after round i"): the rounds' loop is the one FOR that calls G.
    out.append("/-- Section 3.3's statements, with `v` recorded at the end of each round (the appendix's")
    out.append("`after round` values). -/")
    out.append("def BLAKE3_COMPRESS_TRACE (h : Vector Word 8) (m : Vector Word 16) (t : Counter) (len flags : Word) :")
    out.append("    Array (Vector Word 16) := Id.run do")
    out.append("  let mut v : Vector Word 16 := Vector.replicate 16 0")
    out.append("  let mut m := m")
    out.append("  let mut trace : Array (Vector Word 16) := #[]")
    traced = body(c_body, 1)
    k = next(i for i, line in enumerate(traced) if line.startswith("  for _ in"))
    j = next(i for i in range(k + 1, len(traced)) if not traced[i].startswith("    "))
    traced = traced[:j] + ["    trace := trace.push v"] + traced[j:]
    traced = [line for line in traced if line.strip() != "return v"]
    out += traced[:next(i for i in range(j + 1, len(traced)) if traced[i].startswith("  for i in"))]
    out.append("  return trace")
    out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def splice(lean, generated):
    i, j = lean.index(BEGIN), lean.index(END) + len(END) + 1
    return lean[:i] + generated + lean[j:]


def main():
    md = open(sys.argv[1]).read()
    try:
        g = generate(md)
    except Refused as e:
        sys.exit(f"generate.py refused BLAKE3.md: {e}")
    if "--write" in sys.argv:
        path = __file__.replace("generate.py", "Blake3.lean")
        new = splice(open(path).read(), g)
        open(path, "w").write(new)
    else:
        sys.stdout.write(g)


if __name__ == "__main__":
    main()
